"""Independent research core for the resilient AI agents thesis."""

from .agents import (
    ROBUST_PLAN_SCHEMA_VERSION,
    TABULAR_Q_CHECKPOINT_SCHEMA_VERSION,
    RectangularRobustValueIterationAgent,
    RobustStateAction,
    RobustTransitionOutcome,
    RobustTransitionRow,
    RobustValueIterationConfig,
    TabularQLearningAgent,
    TabularQLearningConfig,
)
from .analysis import (
    ANALYSIS_SCHEMA_VERSION,
    AnalysisResult,
    DerivedRunRecords,
    build_analysis_payload,
    derive_completed_run_records,
    validate_analysis,
    write_analysis,
)
from .contracts import (
    Agent,
    AgentTransition,
    ChangeEvent,
    ExperimentSpec,
    GroundTruthTransition,
    InformationPolicy,
    ProtocolStage,
    RetentionPolicy,
    ScenarioSpec,
)
from .experiment_runner import (
    HEADLESS_RUNNER_SCHEMA_VERSION,
    ExperimentTimeoutError,
    HeadlessExperimentRequest,
    HeadlessExperimentRunner,
    HeadlessRunResult,
)
from .gridworld import (
    GRIDWORLD_SCHEMA_VERSION,
    GridAction,
    GridWorldEnvironment,
    GridWorldGymEnv,
    ResolvedGridWorldScenario,
    gridworld_scenario_from_dict,
    gridworld_scenario_json,
    gridworld_scenario_to_dict,
)
from .pilot_protocol import (
    PILOT_PROTOCOL_SCHEMA_VERSION,
    PilotProtocol,
    load_pilot_protocol,
)
from .randomness import derive_scoped_seed

__all__ = [
    "ANALYSIS_SCHEMA_VERSION",
    "GRIDWORLD_SCHEMA_VERSION",
    "HEADLESS_RUNNER_SCHEMA_VERSION",
    "PILOT_PROTOCOL_SCHEMA_VERSION",
    "ROBUST_PLAN_SCHEMA_VERSION",
    "TABULAR_Q_CHECKPOINT_SCHEMA_VERSION",
    "Agent",
    "AgentTransition",
    "AnalysisResult",
    "ChangeEvent",
    "DerivedRunRecords",
    "ExperimentSpec",
    "ExperimentTimeoutError",
    "GridAction",
    "GridWorldEnvironment",
    "GridWorldGymEnv",
    "GroundTruthTransition",
    "HeadlessExperimentRequest",
    "HeadlessExperimentRunner",
    "HeadlessRunResult",
    "InformationPolicy",
    "PilotProtocol",
    "ProtocolStage",
    "RectangularRobustValueIterationAgent",
    "ResolvedGridWorldScenario",
    "RetentionPolicy",
    "RobustStateAction",
    "RobustTransitionOutcome",
    "RobustTransitionRow",
    "RobustValueIterationConfig",
    "ScenarioSpec",
    "TabularQLearningAgent",
    "TabularQLearningConfig",
    "build_analysis_payload",
    "derive_completed_run_records",
    "derive_scoped_seed",
    "gridworld_scenario_from_dict",
    "gridworld_scenario_json",
    "gridworld_scenario_to_dict",
    "load_pilot_protocol",
    "validate_analysis",
    "write_analysis",
]
