import sys
import shutil
import zipfile
from pathlib import Path

def write_evidence_map(staging_dir: Path):
    map_content = """# Thesis Evidence Map

This package contains the frozen, immutable evidence generated by WP6. 

## 1. Protocol & Method Claims
- **Machine Protocol**: `protocol/protocol-v1.0.json` (The frozen execution definition)
- **Human Protocol**: `protocol/PROTOCOL_V1_0.md` (The verified thesis documentation)

## 2. Statistical Analysis & Estimands
Computed directly from the frozen runs and stored in `analysis/units.jsonl`.
Aggregated metrics and estimators are preserved in `analysis/analysis.json`.

## 3. Final Artifacts (Figures & Tables)
- **Figure 1 (Cumulative Deficit)**: `artifacts/cumulative_deficit_boxplot.html`
- **Figure 2 (Immediate Degradation)**: `artifacts/immediate_degradation_boxplot.html`
- **Tables 1 & 2**: `artifacts/primary_metrics.csv` and `artifacts/aggregated_summary.csv`

## 4. Run Registry & Provenance
The exact 14 final evaluation runs are tracked in `freeze-manifest.json`.
Each run object specifies its exact GitHub commit (which is reachable via the `archive/final-campaign-execution` branch) and cryptographically secure SHA-256 hashes of the run payload.
There are no excluded or cherry-picked runs; all 14 execution slots completed validly and are included.

## 5. Forensic Audit Records
- **Checksum Audit**: `forensics/forensic_checksum_audit.md` and `forensics/forensic_checksum_audit_summary.json`
- **Provenance Audit**: `forensics/forensic_provenance_audit.md`
- **UI Validation**: `forensics/t511_ui_validation_log.txt`

## 6. Inference Scope Declaration
No post-hoc inferential statistical tests, p-values, or confidence intervals were generated after unblinding the final results. All descriptive outputs are strictly bound to the pre-declared estimands in `protocol-v1.0.json`. The thesis text must not introduce unsupported confirmatory inferential claims.
"""
    (staging_dir / "THESIS_EVIDENCE_MAP.md").write_text(map_content, encoding="utf-8")


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    
    thesis_final_dir = repo_root / "results" / "thesis-final"
    summaries_dir = repo_root / "results" / "summaries" / "thesis-final-analysis"
    
    if not thesis_final_dir.exists() or not summaries_dir.exists():
        print("Missing required frozen directories.", file=sys.stderr)
        return 1
        
    staging_dir = repo_root / "results" / "evidence-package-staging"
    if staging_dir.exists():
        shutil.rmtree(staging_dir)
    staging_dir.mkdir(parents=True)
    
    # 1. Protocols
    (staging_dir / "protocol").mkdir()
    shutil.copy2(repo_root / "configs" / "protocols" / "protocol-v1.0.json", staging_dir / "protocol" / "protocol-v1.0.json")
    shutil.copy2(repo_root / "docs" / "experiments" / "PROTOCOL_V1_0.md", staging_dir / "protocol" / "PROTOCOL_V1_0.md")
    
    # 2. Analysis
    shutil.copytree(summaries_dir, staging_dir / "analysis")
    
    # 3. Artifacts
    shutil.copytree(thesis_final_dir / "artifacts", staging_dir / "artifacts")
    
    # 4. Freeze Manifest
    shutil.copy2(thesis_final_dir / "freeze-manifest.json", staging_dir / "freeze-manifest.json")
    
    # 5. Forensics
    (staging_dir / "forensics").mkdir()
    shutil.copy2(repo_root / "results" / "forensic_checksum_audit.md", staging_dir / "forensics" / "forensic_checksum_audit.md")
    shutil.copy2(repo_root / "results" / "forensic_checksum_audit_summary.json", staging_dir / "forensics" / "forensic_checksum_audit_summary.json")
    shutil.copy2(repo_root / "results" / "forensic_provenance_audit.md", staging_dir / "forensics" / "forensic_provenance_audit.md")
    shutil.copy2(repo_root / "results" / "t511_ui_validation_log.txt", staging_dir / "forensics" / "t511_ui_validation_log.txt")
    
    write_evidence_map(staging_dir)
    
    archive_path = repo_root / "results" / "thesis_evidence_package"
    shutil.make_archive(str(archive_path), 'zip', str(staging_dir))
    
    shutil.rmtree(staging_dir)
    
    # 6. Validate the ZIP
    zip_path = Path(f"{archive_path}.zip")
    if not zip_path.exists():
        print("Validation failed: ZIP was not created.")
        return 1
        
    expected_files = [
        "THESIS_EVIDENCE_MAP.md",
        "protocol/protocol-v1.0.json",
        "protocol/PROTOCOL_V1_0.md",
        "analysis/units.jsonl",
        "analysis/analysis.json",
        "artifacts/cumulative_deficit_boxplot.html",
        "artifacts/immediate_degradation_boxplot.html",
        "artifacts/primary_metrics.csv",
        "artifacts/aggregated_summary.csv",
        "freeze-manifest.json",
        "forensics/forensic_checksum_audit.md",
        "forensics/forensic_checksum_audit_summary.json",
        "forensics/forensic_provenance_audit.md",
        "forensics/t511_ui_validation_log.txt",
    ]
    
    with zipfile.ZipFile(zip_path, 'r') as zf:
        members = set(zf.namelist())
        for expected in expected_files:
            # Handle possible backslashes on windows in zip (though zip standard is forward slash)
            expected_fwd = expected.replace("\\", "/")
            if expected_fwd not in members:
                print(f"Validation failed: Mapped target {expected} is missing from the ZIP archive!")
                return 1
                
    print(f"Evidence package successfully created and validated: {zip_path.name}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
