import sys
import shutil
from pathlib import Path

def write_evidence_map(staging_dir: Path, repo_root: Path):
    map_content = """# Thesis Evidence Map

This package contains the frozen, immutable evidence generated by WP6. 

## Claim-to-Result Mapping
- **Protocol & Method claims**: Refer to `protocol-v1.0.json` (frozen) and `PROTOCOL_V1_0.md`.
- **Primary Estimands (Deficit, Degradation)**: Computed directly from the frozen runs and stored in `analysis/units.jsonl`.
- **Figure 1 (Cumulative Deficit)**: `artifacts/cumulative_deficit_boxplot.html`
- **Figure 2 (Immediate Degradation)**: `artifacts/immediate_degradation_boxplot.html`
- **Tables 1 & 2**: `artifacts/primary_metrics.csv` and `artifacts/aggregated_summary.csv`

## Run Registry & Provenance
The exact 14 final evaluation runs are tracked in `thesis-final/freeze-manifest.json`.
Each run object specifies its exact GitHub commit (which is reachable via the `archive/final-campaign-execution` branch) and cryptographically secure SHA-256 hashes of the run payload.
There are no excluded or cherry-picked runs; all 14 execution slots completed validly and are included.

## Reproducibility
The data and figures herein can be fully reproduced by checking out the main branch at the WP6 completion point and running:
1. `uv run python scripts/analyze_frozen_evidence.py`
2. `uv run python scripts/generate_artifacts.py`
"""
    (staging_dir / "THESIS_EVIDENCE_MAP.md").write_text(map_content, encoding="utf-8")


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    
    thesis_final_dir = repo_root / "results" / "thesis-final"
    summaries_dir = repo_root / "results" / "summaries" / "thesis-final-analysis"
    
    if not thesis_final_dir.exists() or not summaries_dir.exists():
        print("Missing required frozen directories.", file=sys.stderr)
        return 1
        
    staging_dir = repo_root / "results" / "evidence-package-staging"
    if staging_dir.exists():
        shutil.rmtree(staging_dir)
    staging_dir.mkdir(parents=True)
    
    shutil.copytree(thesis_final_dir, staging_dir / "thesis-final")
    shutil.copytree(summaries_dir, staging_dir / "analysis")
    
    write_evidence_map(staging_dir, repo_root)
    
    archive_path = repo_root / "results" / "thesis_evidence_package"
    shutil.make_archive(str(archive_path), 'zip', str(staging_dir))
    
    shutil.rmtree(staging_dir)
    print(f"Evidence package created: {archive_path.name}.zip")
    
    # Validation step
    if not Path(f"{archive_path}.zip").exists():
        print("Validation failed: ZIP was not created.")
        return 1
        
    return 0

if __name__ == "__main__":
    sys.exit(main())
